name: Build Custom ROM

on:
  push:
    branches:
      - main  # Replace 'main' with your target branch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout Repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # Step 2: Set Up Environment Variables
      - name: Set up environment variables
        run: |
          echo "Setting up environment variables"
          echo "HOME=/home/aghora" >> $GITHUB_ENV
          echo "LOS_DIR=/home/aghora/los" >> $GITHUB_ENV

      # Step 3: Verify Directory Access (Debugging Step)
      - name: Debug Directory Access
        run: |
          echo "Current directory: $(pwd)"
          echo "Home directory contents:"
          ls -l $HOME
          echo "LOS directory contents:"
          ls -l $LOS_DIR || echo "Directory $LOS_DIR does not exist!"

      # Step 4: Prepare Directory (if necessary)
      - name: Ensure LOS Directory Exists
        run: |
          if [ ! -d "$LOS_DIR" ]; then
            echo "LOS directory not found. Creating it."
            mkdir -p $LOS_DIR
          else
            echo "LOS directory exists."
          fi
          echo "Final LOS directory contents:"
          ls -l $LOS_DIR

      # Step 5: Run Build Script
      - name: Execute Build Script
        run: |
          cd /home/aghora/los/
          source build/envsetup.sh
          lunch lineage_vitamin-ap2a-userdebug
          make bacon -j20

      # Step 6: Upload Build Artifacts (Optional)
      - name: Upload Build Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: rom-build
          path: $LOS_DIR/output
